/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum CardsByStatus {
    IN_WORK = 0,
    IN_WORK_EXPIRE = 1,
    IN_WORK_EXPIRE_SOON = 2,
    COMPLETED = 3,
    OUT_CONTROL = 4
}
