/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum DocumentExecutionOwnerType {
    AUTHOR = 0,
    RESPONSIBLE = 1,
    EXECUTOR = 2,
    VIEWER = 3,
    SPECTATOR = 4,
    SYSTEM = 5,
    ADDITIONAL_CONFIRMER = 6,
    PERIODICAL_DISABLE = 7,
    ANSWERER = 8,
    REQUESTER = 9
}
