/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as NotificationTransportDestinationType from "./NotificationTransportDestinationType";
export interface INotificationTransportTypeArgs {
    key?: string;
    caption?: string;
    destination?: Set<NotificationTransportDestinationType.NotificationTransportDestinationType>;
}
export class NotificationTransportType {
    public key?: string;
    public caption?: string;
    public destination?: Set<NotificationTransportDestinationType.NotificationTransportDestinationType>;
    constructor(args?: INotificationTransportTypeArgs) {
        if (args != null && args.key != null) {
            this.key = args.key;
        }
        if (args != null && args.caption != null) {
            this.caption = args.caption;
        }
        if (args != null && args.destination != null) {
            this.destination = args.destination;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("NotificationTransportType");
        if (this.key != null) {
            output.writeFieldBegin("key", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.key);
            output.writeFieldEnd();
        }
        if (this.caption != null) {
            output.writeFieldBegin("caption", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.caption);
            output.writeFieldEnd();
        }
        if (this.destination != null) {
            output.writeFieldBegin("destination", thrift.Thrift.Type.SET, 3);
            output.writeSetBegin(thrift.Thrift.Type.I32, this.destination.size);
            this.destination.forEach((value_1: NotificationTransportDestinationType.NotificationTransportDestinationType): void => {
                output.writeI32(value_1);
            });
            output.writeSetEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): NotificationTransportType {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.key = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.caption = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.SET) {
                        const value_4: Set<NotificationTransportDestinationType.NotificationTransportDestinationType> = new Set<NotificationTransportDestinationType.NotificationTransportDestinationType>();
                        const metadata_1: thrift.TSet = input.readSetBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_5: NotificationTransportDestinationType.NotificationTransportDestinationType = input.readI32();
                            value_4.add(value_5);
                        }
                        input.readSetEnd();
                        _args.destination = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new NotificationTransportType(_args);
    }
}
