/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as VoteParticipantType from "./VoteParticipantType";
import * as __ROOT_NAMESPACE__ from "./";
export interface IVoteParticipantArgs {
    id?: string;
    voteId?: string;
    participantType?: VoteParticipantType.VoteParticipantType;
    user?: __ROOT_NAMESPACE__.UserOrGroup;
}
export class VoteParticipant {
    public id?: string;
    public voteId?: string;
    public participantType?: VoteParticipantType.VoteParticipantType;
    public user?: __ROOT_NAMESPACE__.UserOrGroup;
    constructor(args?: IVoteParticipantArgs) {
        if (args != null && args.id != null) {
            this.id = args.id;
        }
        if (args != null && args.voteId != null) {
            this.voteId = args.voteId;
        }
        if (args != null && args.participantType != null) {
            this.participantType = args.participantType;
        }
        if (args != null && args.user != null) {
            this.user = args.user;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("VoteParticipant");
        if (this.id != null) {
            output.writeFieldBegin("id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.id);
            output.writeFieldEnd();
        }
        if (this.voteId != null) {
            output.writeFieldBegin("voteId", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.voteId);
            output.writeFieldEnd();
        }
        if (this.participantType != null) {
            output.writeFieldBegin("participantType", thrift.Thrift.Type.I32, 3);
            output.writeI32(this.participantType);
            output.writeFieldEnd();
        }
        if (this.user != null) {
            output.writeFieldBegin("user", thrift.Thrift.Type.STRUCT, 4);
            this.user.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): VoteParticipant {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.voteId = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: VoteParticipantType.VoteParticipantType = input.readI32();
                        _args.participantType = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_4: __ROOT_NAMESPACE__.UserOrGroup = __ROOT_NAMESPACE__.UserOrGroup.read(input);
                        _args.user = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new VoteParticipant(_args);
    }
}
