import { Fragment, JSX } from "react";
import Users from "../../Form/Users";
import TextArea from "../../Form/TextArea";
import Checkbox from "../../Form/Checkbox";
import DateTimePicker from "../../Form/DateTimePicker";
import { Control, useFieldArray, UseFormGetValues, useWatch } from "react-hook-form";
import { ContentHolder, DocumentAccessPolicy, DocumentAccessPolicyType, DocumentPattern, FilterCondition, FilterFieldType, FilterItem } from "../../../api/data";
import { includes, map } from "lodash";
import Holder from "../../Form/Holder";
import Input from "../../Form/Input";
import { accessWithPolicy, hasRole } from "../../../utils";
import ScGrifs from "../../Form/ScGrifs";
import DocRelations from "../../Form/DocRelations";
import InboxDoc from "../../Form/InboxDoc";
import { useTranslation } from "react-i18next";

type TabInfoProps = {
  control: Control,
  pattern: DocumentPattern,
  watch: any,
  formEdit: string | null,
  setChanges: (newValue: []) => void,
  notRemoveScIds?: string[],
  getValues: UseFormGetValues<any>
};

const FORM_EDIT_TYPE = ['inbox_simple', 'inbox_simple_not_required', 'inbox'];

const TabInfo = ({ control, pattern, setChanges, formEdit, notRemoveScIds = [], getValues }: TabInfoProps): JSX.Element => {
  const [document, scGrifs, controlUsers] = useWatch({
    control,
    name: ['document', 'scGrifs', 'controlUsers'],
  });

  const { t } = useTranslation();

  const holdersField = useFieldArray({
    control,
    name: 'holders',
  });

  return <>
    <Users
      name={"author"}
      control={control}
      multiple={false}
      label={t('MobileCreateDoc.author')}
      disabled={true}
      changeProps={{
        patternId: null,
        selected: [],
        scGrifs: scGrifs,
        filters: [],
        types: []
      }}
    />
    {pattern?.useSC && <ScGrifs
      name={"scGrifs"}
      control={control}
      label={t('MobileCreateDoc.scGrifs')}
      notRemoveIds={notRemoveScIds}
      disabled={!(hasRole('USER_DOC_SC_UPDATE') || hasRole('ADMIN_DOC_SC_UPDATE'))}
      formItemProps={{
        required: true
      }}
    />}
    {!pattern?.autoGenerateDocName && <TextArea
      label={t('MobileCreateDoc.nameDocument')}
      name={"document.nameDocument"}
      control={control}
      showCount
      maxLength={2000}
      formItemProps={{
        required: true
      }}
    />}

    {includes(FORM_EDIT_TYPE, formEdit) && <InboxDoc
      control={control}
      name={"document"}
      documentId={document.id}
      required={'inbox_simple_not_required' !== formEdit}
    />}

    {pattern.useDocNumber && <Input
      label={t('MobileCreateDoc.numberDocument')}
      name={"document.numberDocument"}
      control={control}
    />}
    {(hasRole('USER_DOC_RESPONSIBLE_UPDATE') || hasRole('ADMIN_DOC_RESPONSIBLE_UPDATE')) && <Checkbox
      label={t('MobileCreateDoc.controlForDocument')}
      name={"document.controlForDocument"}
      control={control}
    />}
    {document.controlForDocument && (
      <>
        <Users
          name={"controlUsers"}
          control={control}
          multiple={false}
          label={t('MobileCreateDoc.controlUsers')}
          changeProps={{
            useFavorite: true,
            patternId: pattern?.id || null,
            filters: [
              new FilterItem({
                field: 'VIEW',
                value: pattern?.id,
                fType: FilterFieldType.STRING,
                condition: FilterCondition.EQUAL
              })
            ],
            selected: controlUsers,
            scGrifs: scGrifs,
            types: ['users', 'scs']
          }}
        />
        <DateTimePicker
          name={"document.documentDeadlineDate"}
          control={control}
          label={t('MobileCreateDoc.controlUsers')}
          time={true}
          formItemProps={{
            required: true
          }}
        />
      </>
    )}
    {map(holdersField.fields, (holder: ContentHolder, index: number) => {
      return <Fragment key={holder.id}>
        {holder.showInInfo && <Holder
          holder={holder}
          name={`holders.${index}`}
          control={control}
          setChanges={setChanges}
          patternId={pattern.id}
          getValues={getValues}
        />}
      </Fragment>
    })}
    {accessWithPolicy(new DocumentAccessPolicy({
      type: DocumentAccessPolicyType.ACCESS
    }), 'USER_DOC_RELATIONS_UPDATE', 'ADMIN_DOC_RELATIONS_UPDATE') && <DocRelations
        name={"docRelations"}
        control={control}
        label={t('MobileCreateDoc.docRelations')}
        documentId={document.id}
      />}
  </>;
};


export default TabInfo;