/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum AccountDefineConf {
    GROUP_ALL = 0,
    DECISION_DICT = 1,
    A4_TEMPLATE_DICT = 2
}
