/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 from "node-int64";
import * as thrift from "thrift";
import * as AnaliticsDashboard from "./AnaliticsDashboard";
export interface IAnaliticsDashboardPageArgs {
    analiticsDashboardList?: Array<AnaliticsDashboard.AnaliticsDashboard>;
    count?: number | Int64;
}
export class AnaliticsDashboardPage {
    public analiticsDashboardList?: Array<AnaliticsDashboard.AnaliticsDashboard>;
    public count?: Int64;
    constructor(args?: IAnaliticsDashboardPageArgs) {
        if (args != null && args.analiticsDashboardList != null) {
            this.analiticsDashboardList = args.analiticsDashboardList;
        }
        if (args != null && args.count != null) {
            if (typeof args.count === "number") {
                this.count = new Int64(args.count);
            }
            else {
                this.count = args.count;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("AnaliticsDashboardPage");
        if (this.analiticsDashboardList != null) {
            output.writeFieldBegin("analiticsDashboardList", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.analiticsDashboardList.length);
            this.analiticsDashboardList.forEach((value_1: AnaliticsDashboard.AnaliticsDashboard): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.count != null) {
            output.writeFieldBegin("count", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.count);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): AnaliticsDashboardPage {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_2: Array<AnaliticsDashboard.AnaliticsDashboard> = new Array<AnaliticsDashboard.AnaliticsDashboard>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_3: AnaliticsDashboard.AnaliticsDashboard = AnaliticsDashboard.AnaliticsDashboard.read(input);
                            value_2.push(value_3);
                        }
                        input.readListEnd();
                        _args.analiticsDashboardList = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_4: Int64 = input.readI64();
                        _args.count = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new AnaliticsDashboardPage(_args);
    }
}
