/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as AvailableFileStorageParam from "./AvailableFileStorageParam";
export interface IAvailableFileStorageArgs {
    key?: string;
    name?: string;
    settingsFile?: Buffer;
    params?: Array<AvailableFileStorageParam.AvailableFileStorageParam>;
}
export class AvailableFileStorage {
    public key?: string;
    public name?: string;
    public settingsFile?: Buffer;
    public params?: Array<AvailableFileStorageParam.AvailableFileStorageParam>;
    constructor(args?: IAvailableFileStorageArgs) {
        if (args != null && args.key != null) {
            this.key = args.key;
        }
        if (args != null && args.name != null) {
            this.name = args.name;
        }
        if (args != null && args.settingsFile != null) {
            this.settingsFile = args.settingsFile;
        }
        if (args != null && args.params != null) {
            this.params = args.params;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("AvailableFileStorage");
        if (this.key != null) {
            output.writeFieldBegin("key", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.key);
            output.writeFieldEnd();
        }
        if (this.name != null) {
            output.writeFieldBegin("name", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.name);
            output.writeFieldEnd();
        }
        if (this.settingsFile != null) {
            output.writeFieldBegin("settingsFile", thrift.Thrift.Type.STRING, 3);
            output.writeBinary(this.settingsFile);
            output.writeFieldEnd();
        }
        if (this.params != null) {
            output.writeFieldBegin("params", thrift.Thrift.Type.LIST, 4);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.params.length);
            this.params.forEach((value_1: AvailableFileStorageParam.AvailableFileStorageParam): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): AvailableFileStorage {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.key = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.name = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: Buffer = input.readBinary();
                        _args.settingsFile = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_5: Array<AvailableFileStorageParam.AvailableFileStorageParam> = new Array<AvailableFileStorageParam.AvailableFileStorageParam>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_6: AvailableFileStorageParam.AvailableFileStorageParam = AvailableFileStorageParam.AvailableFileStorageParam.read(input);
                            value_5.push(value_6);
                        }
                        input.readListEnd();
                        _args.params = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new AvailableFileStorage(_args);
    }
}
