/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum AvailablePatternStageType {
    INTERNAL = 0,
    AUTO = 1,
    EXTERNAL = 2,
    SUB_PATTERN = 3,
    REPORT = 4,
    HIDDEN = 5,
    WAIT_CHILD_DOCS = 6,
    CREATE_CHILD_BY_ROLE = 7,
    EMAIL = 8,
    SMS = 9,
    DISCUSSION_AUTO = 10
}
