/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum DecisionType {
    NULL = 0,
    YES = 1,
    NO = 2,
    OTHER_TIME = 3
}
