/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as DocumentAccessPolicyType from "./DocumentAccessPolicyType";
export interface IDocumentAccessPolicyArgs {
    type?: DocumentAccessPolicyType.DocumentAccessPolicyType;
    policyId?: string;
}
export class DocumentAccessPolicy {
    public type?: DocumentAccessPolicyType.DocumentAccessPolicyType;
    public policyId?: string;
    constructor(args?: IDocumentAccessPolicyArgs) {
        if (args != null && args.type != null) {
            this.type = args.type;
        }
        if (args != null && args.policyId != null) {
            this.policyId = args.policyId;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("DocumentAccessPolicy");
        if (this.type != null) {
            output.writeFieldBegin("type", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.type);
            output.writeFieldEnd();
        }
        if (this.policyId != null) {
            output.writeFieldBegin("policyId", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.policyId);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): DocumentAccessPolicy {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: DocumentAccessPolicyType.DocumentAccessPolicyType = input.readI32();
                        _args.type = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.policyId = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new DocumentAccessPolicy(_args);
    }
}
