/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum KnowledgeDocumentStatus {
    ACTIVE = 0,
    CANCELED = 1,
    EDITED = 2
}
