/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum KnowledgeHistoryParamType {
    KNOWLEDGE_TREE_NODE = 0,
    KNOWLEDGE_TREE_DOCUMENT = 1,
    KNOWLEDGE_USER = 2,
    KNOWLEDGE_GROUP = 3
}
