/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum PatternRoles {
    VIEW = 0,
    CREATE = 1,
    INBOX = 2,
    OUTBOX = 3,
    ADMIN = 4
}
