/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum PatternType {
    DOCUMENT = 0,
    DISCUSSION_FLOW = 1,
    DISCUSSION_QUESTION = 2,
    DISCUSSION_PROTOCOL = 3,
    USER_CONTENT = 4,
    EXTERNAL = 5
}
