/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as core from "./";
export interface IReportTemplateLinkArgs {
    id?: string;
    reportId?: string;
    patternId?: string;
    userOrGroup?: core.UserOrGroup;
}
export class ReportTemplateLink {
    public id?: string;
    public reportId?: string;
    public patternId?: string;
    public userOrGroup?: core.UserOrGroup;
    constructor(args?: IReportTemplateLinkArgs) {
        if (args != null && args.id != null) {
            this.id = args.id;
        }
        if (args != null && args.reportId != null) {
            this.reportId = args.reportId;
        }
        if (args != null && args.patternId != null) {
            this.patternId = args.patternId;
        }
        if (args != null && args.userOrGroup != null) {
            this.userOrGroup = args.userOrGroup;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ReportTemplateLink");
        if (this.id != null) {
            output.writeFieldBegin("id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.id);
            output.writeFieldEnd();
        }
        if (this.reportId != null) {
            output.writeFieldBegin("reportId", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.reportId);
            output.writeFieldEnd();
        }
        if (this.patternId != null) {
            output.writeFieldBegin("patternId", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.patternId);
            output.writeFieldEnd();
        }
        if (this.userOrGroup != null) {
            output.writeFieldBegin("userOrGroup", thrift.Thrift.Type.STRUCT, 4);
            this.userOrGroup.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ReportTemplateLink {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.reportId = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.patternId = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_4: core.UserOrGroup = core.UserOrGroup.read(input);
                        _args.userOrGroup = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ReportTemplateLink(_args);
    }
}
