/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum SearchType {
    S_LIKE = 0,
    S_LIKE_SEMANTIC = 1,
    S_ALL = 2,
    S_ALL_SEMANTIC = 3,
    S_ANY = 4,
    S_ANY_SEMANTIC = 5
}
