/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as core from "./";
export interface IUserObserverArgs {
    id?: string;
    observer?: core.UserOrGroup;
    observedUser?: core.UserOrGroup;
}
export class UserObserver {
    public id?: string;
    public observer?: core.UserOrGroup;
    public observedUser?: core.UserOrGroup;
    constructor(args?: IUserObserverArgs) {
        if (args != null && args.id != null) {
            this.id = args.id;
        }
        if (args != null && args.observer != null) {
            this.observer = args.observer;
        }
        if (args != null && args.observedUser != null) {
            this.observedUser = args.observedUser;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("UserObserver");
        if (this.id != null) {
            output.writeFieldBegin("id", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.id);
            output.writeFieldEnd();
        }
        if (this.observer != null) {
            output.writeFieldBegin("observer", thrift.Thrift.Type.STRUCT, 2);
            this.observer.write(output);
            output.writeFieldEnd();
        }
        if (this.observedUser != null) {
            output.writeFieldBegin("observedUser", thrift.Thrift.Type.STRUCT, 3);
            this.observedUser.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): UserObserver {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.id = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_2: core.UserOrGroup = core.UserOrGroup.read(input);
                        _args.observer = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_3: core.UserOrGroup = core.UserOrGroup.read(input);
                        _args.observedUser = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new UserObserver(_args);
    }
}
