/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
export enum VoteParticipantType {
    VOTER = 0,
    SECRETARY = 1,
    CHAIRMAN = 2
}
